/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocounterstrike.gui.usuario;
import projetocounterstrike.Controle;
import projetocounterstrike.model.Compra;
import projetocounterstrike.model.Jogador;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author ruan_
 */
public class JPanelFormulario extends javax.swing.JPanel {

            private JPanelUsuario pnlUsuario;
            private Controle controle;
            private String tipoPessoa = null;    
    
            public JPanelFormulario(JPanelUsuario pnlUsuario, Controle controle) {
        
                        this.pnlUsuario = pnlUsuario;
                        this.controle = controle;
                        initComponents();
            }
            
            public Jogador getFormulario(){
        
                        //validacao do formulario
                         if(txfCPF.getText().trim().length() == 11 && 
                            new String(psfSenha.getPassword()).trim().length() > 3 && 
                            txfNome.getText().trim().length() > 0){

                            Jogador u = new Jogador();
                            u.setNickname(txfCPF.getText().trim());
                            u.setSenha(new String(psfSenha.getPassword()).trim());
                            if(cbxCidade.getSelectedIndex() > 0){//verifica se o Usuário indicou alguma cidade para o registro.
                                u.setCompra((List<Compra>) (Compra) cbxCidade.getSelectedItem());
                            } 

                            return u;
                         }

                         return null;
            }
            
            public void populaFormulario(Jogador u){
        
                        if(u == null){//se o parametro estiver nullo, limpa o formulario
                            txfCPF.setText("");
                            cbxCidade.setSelectedIndex(0);
                            psfSenha.setText(""); 

                        }else{
                            txfCPF.setText(u.getNickname());
                            cbxCidade.getModel().setSelectedItem(u.getCompra());// o combobox retorna um objeto (aqui chama o equals da classe Cidade)
                            psfSenha.setText(u.getSenha());
                        }
        
            }
            
            public void populaComboCidade(){
        
                        cbxCidade.removeAllItems();//zera o combo

                        DefaultComboBoxModel model =  (DefaultComboBoxModel) cbxCidade.getModel();

                        model.addElement("Selecione"); //primeiro item        
                        try {
                            List<Compra> listCidades = controle.getConexaoJDBC().getCompras();
                            
                            for(Compra c : listCidades){
                                model.addElement(c);
                            }

                        } catch (Exception ex) {

                            JOptionPane.showMessageDialog(this, "Erro ao listar Cidades -:"+ex.getLocalizedMessage(), "Cidades", JOptionPane.ERROR_MESSAGE);
                            ex.printStackTrace();
                        }                
            }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JTpUsuario = new javax.swing.JTabbedPane();
        pnlDados = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        txfCPF = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        lblSenha = new javax.swing.JLabel();
        psfSenha = new javax.swing.JPasswordField();
        pnlSul = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlPermissoes = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlDados.setLayout(new java.awt.BorderLayout());

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblCPF.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblCPF, gridBagConstraints);

        txfCPF.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfCPF, gridBagConstraints);

        lblNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblNome, gridBagConstraints);

        txfNome.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfNome, gridBagConstraints);

        lblCidade.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        pnlCentro.add(lblCidade, gridBagConstraints);

        cbxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(cbxCidade, gridBagConstraints);

        lblSenha.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblSenha, gridBagConstraints);

        psfSenha.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(psfSenha, gridBagConstraints);

        pnlDados.add(pnlCentro, java.awt.BorderLayout.CENTER);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlSul.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSul.add(btnCancelar);

        pnlDados.add(pnlSul, java.awt.BorderLayout.SOUTH);

        JTpUsuario.addTab("Dados Cadastrais", pnlDados);
        JTpUsuario.addTab("Perfil", pnlPermissoes);

        add(JTpUsuario, java.awt.BorderLayout.CENTER);
        JTpUsuario.getAccessibleContext().setAccessibleName("Formulário");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

            Jogador u = getFormulario();//recupera os dados do formulÃ¡rio
            if(u != null){

                try {

                    u.setData_cadastro(Calendar.getInstance());
                    pnlUsuario.getControle().getConexaoJDBC().persist(u);
                    JOptionPane.showMessageDialog(this, "Usuario armazenado!", "Salvar", JOptionPane.INFORMATION_MESSAGE);

                    pnlUsuario.showTela("tela_listagem");//muda a tela para a listagem

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar Usuário! : "+ex.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
                }

            }else{

                JOptionPane.showMessageDialog(this, "Preencha o formulário!", "Edição", JOptionPane.INFORMATION_MESSAGE);
            }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

            pnlUsuario.showTela("tela_listagem");

    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTpUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlPermissoes;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JPasswordField psfSenha;
    private javax.swing.JTextField txfCPF;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}