/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocounterstrike.gui.usuario;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetocounterstrike.Controle;
import projetocounterstrike.model.Compra;
import projetocounterstrike.model.ItensCompra;

/**
 *
 * @author ruan_
 */
public class JPanelListagem extends javax.swing.JPanel {

    private JPanelCompra pnlCompra;
    private Controle controle;
    
    public JPanelListagem(JPanelCompra pnlCompra, Controle controle) {
        this.pnlCompra = pnlCompra;
        this.controle = controle;
        initComponents();
    }

    public void populaTable(){
        DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel();//recuperacao do modelo da tabela

        model.setRowCount(0);//elimina as linhas existentes (reset na tabela)

        try {
            List<Compra> listComp = controle.getConexaoJDBC().getCompras();
            for(Compra cp : listComp){
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                int quant=0;
                if(cp.getItens()!= null){//como itens é opcional, testa antes recuperar a quantidade de itens da compra
                    Object[] obj = {cp, cp.getJogador(), df.format(cp.getData().getTime()), cp.getValorTotal(), ""};
                    for(ItensCompra ic : cp.getItens()){
                        quant=quant+ic.getQuantidade();
                    }
                    obj[4]=quant;
                    model.addRow((Object[]) obj);
                }else
                    model.addRow(new Object[]{cp, cp.getJogador(), df.format(cp.getData().getTime()), cp.getValorTotal(), ""});
            }

        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao listar Compras -:"+ex.getLocalizedMessage(), "Usuários", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnNovo.setText("Novo");
        btnNovo.setActionCommand("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Jogador Id (Nickname)", "Data Da Compra", "Valor Total", "Quantidade de Itens"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
      
        pnlCompra.showTela("tela_edicao");
        pnlCompra.getTelaEdicao().populaFormulario(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
        if(indice > -1){
                      
            DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table
                        
            Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada
            
            Compra c = (Compra) linha.get(0); //model.addRow...
           
            pnlCompra.showTela("tela_edicao");
            pnlCompra.getTelaEdicao().populaFormulario(c);   
        }else{
              JOptionPane.showMessageDialog(this, "Selecione uma linha para editar!", "Edição", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
            if(indice > -1){

                DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table

                Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada

                Compra u = (Compra) linha.get(0); //model.addRow...

                try {
                    pnlCompra.getControle().getConexaoJDBC().remover(u);
                    JOptionPane.showMessageDialog(this, "Compra removida!", "Compras", JOptionPane.INFORMATION_MESSAGE);
                    populaTable(); //refresh na tabela

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover Compra -:"+ex.getLocalizedMessage(), "Compras", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }                        

            }else{
                  JOptionPane.showMessageDialog(this, "Selecione uma linha para remover!", "Remoção", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTable tblListagem;
    // End of variables declaration//GEN-END:variables

}
