/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocounterstrike.gui.usuario;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetocounterstrike.Controle;
import projetocounterstrike.model.Compra;
import projetocounterstrike.model.ItensCompra;

/**
 *
 * @author ruan_
 */
public class JPanelListagem extends javax.swing.JPanel {

    private JPanelCompra pnlCompra;
    private Controle controle;
    
    public JPanelListagem(JPanelCompra pnlCompra, Controle controle) {
        this.pnlCompra = pnlCompra;
        this.controle = controle;
        initComponents();
    }

    public void populaTable(){
        DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel();//recuperacao do modelo da tabela

        model.setRowCount(0);//elimina as linhas existentes (reset na tabela)

        try {
            List<Compra> listComp = controle.getConexaoJDBC().getCompras();
            for(Compra cp : listComp){
                System.out.println("cp.getItens() : "+ cp.getItens() );
                // vai imprimir apenas o cpf do usuario em função do método toString da classe usuario 
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                int quant=0;
                if(cp.getItens()!= null){//como a cidade é opcional, testa antes recuperar a cidade do Usuario
                    Object[] obj = {cp.getJogador(), df.format(cp.getData().getTime()), cp.getValorTotal(), ""};
                    for(ItensCompra ic : cp.getItens()){
                        quant=quant+ic.getQuantidade();
                    }
                    obj[3]=quant;
                    model.addRow((Object[]) obj);
                }else
                    model.addRow(new Object[]{cp.getJogador(), df.format(cp.getData().getTime()), cp.getValorTotal(), ""});
            }

        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao listar Compras -:"+ex.getLocalizedMessage(), "Usuários", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        lblFiltroNome = new javax.swing.JLabel();
        txfFiltroNome = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltroNome.setText("Filtrar por nickname:");
        pnlNorte.add(lblFiltroNome);

        txfFiltroNome.setColumns(20);
        pnlNorte.add(txfFiltroNome);

        btnFiltrar.setText("Filtrar");
        pnlNorte.add(btnFiltrar);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        btnNovo.setText("Novo");
        btnNovo.setActionCommand("Novo");
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador ID (Nickname)", "Data Da Compra", "Valor Total", "Quantidade de Itens"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblFiltroNome;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txfFiltroNome;
    // End of variables declaration//GEN-END:variables

}
