/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocounterstrike.gui.usuario;

import projetocounterstrike.Controle;

/**
 *
 * @author ruan_
 */
public class JPanelEdicao extends javax.swing.JPanel {

    private JPanelUsuario pnlUsuario;
    private Controle controle;
    
    public JPanelEdicao(JPanelUsuario pnlUsuario, Controle controle) {
        this.pnlUsuario = pnlUsuario;
        this.controle = controle;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSul = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btncCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnSalvar.setText("Salvar");
        pnlSul.add(btnSalvar);

        btncCancelar.setText("Cancelar");
        pnlSul.add(btncCancelar);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());
        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btncCancelar;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    // End of variables declaration//GEN-END:variables
}
